-- begin CARSERVICECENTER_EMPLOYEE
alter table CARSERVICECENTER_EMPLOYEE add constraint FK_CARSERVICECENTER_EMPLOYEE_ON_CENTER foreign key (CENTER_ID) references CARSERVICECENTER_CAR_SERVICE_CENTER(ID)^
create index IDX_CARSERVICECENTER_EMPLOYEE_ON_CENTER on CARSERVICECENTER_EMPLOYEE (CENTER_ID)^
-- end CARSERVICECENTER_EMPLOYEE
-- begin CARSERVICECENTER_CAR_SERVICE_CENTER
alter table CARSERVICECENTER_CAR_SERVICE_CENTER add constraint FK_CARSERVICECENTER_CAR_SERVICE_CENTER_ON_CITY foreign key (CITY_ID) references CARSERVICECENTER_CITY(ID)^
create index IDX_CARSERVICECENTER_CAR_SERVICE_CENTER_ON_CITY on CARSERVICECENTER_CAR_SERVICE_CENTER (CITY_ID)^
-- end CARSERVICECENTER_CAR_SERVICE_CENTER
-- begin CARSERVICECENTER_REPAIR
alter table CARSERVICECENTER_REPAIR add constraint FK_CARSERVICECENTER_REPAIR_ON_EMPLOYEE foreign key (EMPLOYEE_ID) references CARSERVICECENTER_EMPLOYEE(ID)^
alter table CARSERVICECENTER_REPAIR add constraint FK_CARSERVICECENTER_REPAIR_ON_CENTER foreign key (CENTER_ID) references CARSERVICECENTER_CAR_SERVICE_CENTER(ID)^
create index IDX_CARSERVICECENTER_REPAIR_ON_EMPLOYEE on CARSERVICECENTER_REPAIR (EMPLOYEE_ID)^
create index IDX_CARSERVICECENTER_REPAIR_ON_CENTER on CARSERVICECENTER_REPAIR (CENTER_ID)^
-- end CARSERVICECENTER_REPAIR
-- begin CARSERVICECENTER_COMPANY
alter table CARSERVICECENTER_COMPANY add constraint FK_CARSERVICECENTER_COMPANY_ON_ID foreign key (ID) references CARSERVICECENTER_CUSTOMER(ID) on delete CASCADE^
-- end CARSERVICECENTER_COMPANY
-- begin CARSERVICECENTER_INDIVIDUAL
alter table CARSERVICECENTER_INDIVIDUAL add constraint FK_CARSERVICECENTER_INDIVIDUAL_ON_ID foreign key (ID) references CARSERVICECENTER_CUSTOMER(ID) on delete CASCADE^
-- end CARSERVICECENTER_INDIVIDUAL
-- begin CARSERVICECENTER_CAR_SERVICE_CENTER_CUSTOMER_LINK
alter table CARSERVICECENTER_CAR_SERVICE_CENTER_CUSTOMER_LINK add constraint FK_CARSERCENCUS_ON_CUSTOMER foreign key (CUSTOMER_ID) references CARSERVICECENTER_CUSTOMER(ID)^
alter table CARSERVICECENTER_CAR_SERVICE_CENTER_CUSTOMER_LINK add constraint FK_CARSERCENCUS_ON_CAR_SERVICE_CENTER foreign key (CAR_SERVICE_CENTER_ID) references CARSERVICECENTER_CAR_SERVICE_CENTER(ID)^
-- end CARSERVICECENTER_CAR_SERVICE_CENTER_CUSTOMER_LINK
